version: 2

models:
  - name: stg_clickstream
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: session_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['page_view', 'product_view', 'add_to_cart', 'purchase']
      - name: event_timestamp
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
      - name: price
        tests:
          - not_null